// Global using directives

global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text;
global using Azure.Identity;
global using Azure.Storage;
global using Azure.Storage.Blobs;
global using CarManager.Application.Abstractions;
global using CarManager.Application.User.Queries.UserInformation;
global using CarManager.Application.User.Responses;
global using CarManager.Domain.Entities;
global using CarManager.Domain.Enumeration;
global using CarManager.Domain.Repositories;
global using CarManager.Domain.Types;
global using CarManager.Domain.ValueObjects;
global using CarManager.Infrastructure.Blob;
global using CarManager.Infrastructure.Database;
global using CarManager.Infrastructure.Database.Configurations;
global using CarManager.Infrastructure.Database.Options;
global using CarManager.Infrastructure.Database.UnitOfWork;
global using CarManager.Infrastructure.Security;
global using CarManager.Infrastructure.Security.Options;
global using CarManager.Shared.Abstractions.Commands;
global using CarManager.Shared.Abstractions.Common;
global using CarManager.Shared.Abstractions.Primitives;
global using CarManager.Shared.Abstractions.Primitives.Results;
global using CarManager.Shared.Abstractions.Queries;
global using CarManager.Shared.Abstractions.Security;
global using CarManager.Shared.Abstractions.Utility;
global using CarManager.Shared.Infrastructure.Commands;
global using CarManager.Shared.Infrastructure.CqrsDispatcher;
global using CarManager.Shared.Infrastructure.Database;
global using CarManager.Shared.Infrastructure.Queries;
global using CarManager.Shared.Infrastructure.Time;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using JsonWebToken = CarManager.Shared.Abstractions.Security.JsonWebToken;
global using JwtRegisteredClaimNames = Microsoft.IdentityModel.JsonWebTokens.JwtRegisteredClaimNames;
global using JwtRegisteredClaimNames_ = System.IdentityModel.Tokens.Jwt.JwtRegisteredClaimNames;
global using RefreshToken = CarManager.Shared.Abstractions.Security.RefreshToken;